services:
  - type: web
    name: family-cookbook
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DATABASE_URL
        value: sqlite:////var/data/cookbook.db
    # Persist the data folder where SQLite database is stored
    disk:
      name: cookbook-data
      mountPath: /var/data
      sizeGB: 1
